maxcraft_homepage:
    path:     /
    defaults: { _controller: MaxcraftDefaultBundle:Default:index, page: 1}
    requirements:

maxcraft_default_blog:
    path:  /page/{page}
    defaults: { _controller: MaxcraftDefaultBundle:Default:index, page: 1  }
    requirements:
        page:  \d+

maxcraft_register:
    path: /register
    defaults: {_controller: MaxcraftDefaultBundle:Default:register}

maxcraft_myalbums:
    path: /albums
    defaults: {_controller: MaxcraftDefaultBundle:User:myalbums}

maxcraft_album_edit:
    path: /album/{albumId}/edit
    defaults: {_controller: MaxcraftDefaultBundle:User:editAlbum}
    requirements:
        albumId: \d+

uploadimage:
    path: /album/uploadimage/{albumId}
    defaults: {_controller: MaxcraftDefaultBundle:Default:uploadImage}
    requirements:
        albumId: \d+

albumsetimage:
    pattern:  /album/{albumid}/setimage/{imageid}
    defaults: { _controller: MaxcraftDefaultBundle:Default:changeAlbumImage }
    requirements:
        albumid: \d+
        imageid: \d+

imageremove:
    pattern:  /image/{imageid}/remove
    defaults: { _controller: MaxcraftDefaultBundle:Default:removeImage }
    requirements:
        imageid:  \d+

profil:
    path: /profil/{pseudo}
    defaults: {_controller: MaxcraftDefaultBundle:User:profil}

admin_news:
    path: /admin/news
    defaults: {_controller: MaxcraftDefaultBundle:Admin:news}

admin_news_create:
    path: /admin/news/create
    defaults: {_controller: MaxcraftDefaultBundle:Admin:newNews, newsId:null}

admin_news_edit:
    path: /admin/news/{newsId}/edit
    defaults: {_controller: MaxcraftDefaultBundle:Admin:newNews}
    requirements:
        newsId: \d+

admin_infos:
    path: /admin/infos
    defaults: {_controller: MaxcraftDefaultBundle:Admin:infos}

maxcraft_faction:
    path: /faction/{factionTag}
    defaults: {_controller: MaxcraftDefaultBundle:Faction:infos}

maxcraft_faction_create:
    path: /createfaction
    defaults: {_controller: MaxcraftDefaultBundle:Faction:createFaction}



maxcraft_parametres:                                                    # A FAIRE !!!!!!
    path: /parametres
    defaults: {_controller: MaxcraftDefaultBundle:User:parametres}

maxcraft_bugreport:
    path: /bugreport
    defaults: {_controller: MaxcraftDefaultBundle:User:bugReport}

        #en cours


maxcraft_players:
    pattern:  /les-joueurs/{parser}/{page}
    defaults: { _controller: MaxcraftDefaultBundle:Default:players, parser: 'date', page: 1}

maxcraft_factionslist:
    path: /factionslist
    defaults: {_controller: MaxcraftDefaultBundle:Faction:factionsList}

maxcraft_donjons:
    path: /donjons
    defaults: {_controller: MaxcraftDefaultBundle:Default:donjons}

maxcraft_ventes:
    path: /ventes
    defaults: {_controller: MaxcraftDefaultBundle:Shop:ventes}

maxcraft_shop:
    path: /shop
    defaults: {_controller: MaxcraftDefaultBundle:Shop:shop}

maxcraft_vote:
    path: /voter
    defaults: {_controller: MaxcraftDefaultBundle:Default:vote}

maxcraft_messages:
    path: /mp
    defaults: {_controller: MaxcraftDefaultBundle:User:mp}

maxcraft_notifications:
    path: /notifs
    defaults: {_controller: MaxcraftDefaultBundle:User:notifs}

test_menu:
    path: /test/menu
    defaults: {_controller: MaxcraftDefaultBundle:Default:menu}

test_wrap:
    path: /test/wrap
    defaults: {_controller: MaxcraftDefaultBundle:Default:wrap}