maxcraft_homepage:
    path:     /
    defaults: { _controller: MaxcraftDefaultBundle:Default:index, page: 1}
    requirements:

maxcraft_default_blog:
    path:  /page/{page}
    defaults: { _controller: MaxcraftDefaultBundle:Default:index, page: 1  }
    requirements:
        page:  \d+

maxcraft_new_user_and_player:
    path: /new/user
    defaults: { _controller: MaxcraftDefaultBundle:Default:userCreate}

maxcraft_new_comment:
    path:     /new/comment/{user}/{newsId}
    defaults: { _controller: MaxcraftDefaultBundle:Default:commentCreate, user: 1, news: 1}
    requirements:
      user: .+
      newsId: \d+

maxcraft_new_news:
      path: /new/news/{user}

maxcraft_news_test:
      path: /test/news/{newsId}
      defaults: {_controller: MaxcraftDefaultBundle:Default:newsTest, newsId:1}
      requirements:
        newsId: \d+